### PR TITLE
fix arethetypeswrong errors

### LINKED ISSUE #2: The system cannot find the path specified
@waldekmastykarz I am getting `The system cannot find the path specified` error when trying to build the package with `npm run build`. I don't have zsh installed on my machine, so I changed it to bash as shown in below screen. Am I missing anything here?

image

Thanks,
Vishal

### PR DESCRIPTION
**Pull request by SebastienGllmt**
This PR does a few things:

1. It changes the `fix-mjs.sh` string to use a shebang instead of specifying the shell in the `package.json`. This should fix #2 
2. It fixes the error mention in #1 by having separate declaration files for cjs and esm builds
3. It fixes the `fix-mjs.sh` script on non-Mac machines (which have a different behavior for `sed`)
4. It bumps package versions (no deep reason for this, just wanted to make sure it worked on the latest version of typescript)

### CODE REVIEW

**Comment by waldekmastykarz** [comment]
Thanks! I'll have a look in the next few days!

File: scripts/fix-mjs.sh [hunk 1]
```diff
@@ -1,6 +1,28 @@
+#!/bin/bash
+
+echo "Updating .js files..."
 for file in ./dist/esm/*.js; do
   echo "Updating $file contents..."
-  sed -i '' "s/\.js'/\.mjs'/g" "$file"
+  # Use in-place edit correctly for both Linux and macOS
+  if [[ "$OSTYPE" == "darwin"* ]]; then
+    sed -i '' "s/\.js'/\.mjs'/g" "$file" # macOS
```
Comment (SebastienGllmt) [inline scripts/fix-mjs.sh:8]: As a separate issue, I realized this doesn't work if your linter is set to use regular quotes (`"`) instead of single quotes (`'`) because in that case `.js'` won't match (since it will be `.js"`)

This is not an issue introduced in this PR (it's an issue that has existed from the start) so it shouldn't block merging this PR, but it would be nice to fix this as well so either quote type works

File: scripts/fix-mjs.sh
Comment (SebastienGllmt) [inline scripts/fix-mjs.sh:1]: As a separate realization, I just noticed that maybe this entire file is no longer needed if you require all the imports to use `.ts` in your app and then use the new path rewriting feature in Typescript 5.7: https://devblogs.microsoft.com/typescript/announcing-typescript-5-7-rc/#path-rewriting-for-relative-paths

This would be nice since importing with `.ts` directly also makes it easier to use the same library for ESM, CJS and Deno/Bun

**Comment by waldekmastykarz** [comment]
Took me longer than it should, but thanks again for the suggestions! I appreciate your help!
